<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Home</title>
        <!--<meta name="viewport" content="initial-scale=1.0, user-scalable=yes" />-->
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <?php
        //*********************************************
        // Database stuff - all done with PHP
        //*********************************************

        // STEP 1: Connect to the database 
        // Don't forget to fill in your own:
        //	username, password and database name)

        $db = new mysqli("localhost", "root", "", "capstone");
        if (mysqli_connect_errno())
        {
            printf("Connect failed: %s\n", mysqli_connect_error());
            exit();
        }

        // STEP 2: Query the table with the marker information

        $res = $db->query("select * from patient");

        // STEP 3: Store the marker info in arrays for each row found
        // save the count of markers for later

        $mrk_cnt = 0;
        while ($obj = $res->fetch_object())                 // get all rows (markers)
        {
            $latitude[$mrk_cnt]     = $obj->latitude;       // save the lattitude
            $longtitude[$mrk_cnt]   = $obj->longtitude;     // save the longitude
            $address[$mrk_cnt]      = $obj->address;
            // $name[$mrk_cnt]         = $obj->name;         // save the info-window
            $mrk_cnt++;                                     // increment the marker counter
        }
        $res->close();
        // Now we have the lattitude, longitude and info-window text for each marker 
        // stored in php arrays. Now we need to write the marker's JavaScript 
        // dynamically with this information
    ?>

    <script type='text/javascript'>
        var point;
        var mrktx;

        function load()
        {
            addTo = 0;
            var latlng = new google.maps.LatLng(7.147905, 125.582657);
            var myOptions = {
                zoom: 11,
                center: latlng,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            // NOTE: all values: latitude, longitude, zoom, etc.
            // should also come from the database for flexibility

            var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
            // This next block of JavaScript needs to be generated by PHP 
            // to 'add-in' the information from the arrays
            

            <?php
                for ($lcnt = 0; $lcnt < $mrk_cnt; $lcnt++)
                {
                    echo "var point$lcnt = new google.maps.LatLng($latitude[$lcnt], $longtitude[$lcnt]);\n";
                    echo "var mrktx$lcnt = \"$address[$lcnt]\";\n";
                    echo "var infowindow$lcnt = new google.maps.InfoWindow({content: mrktx$lcnt});";
                    echo "var marker$lcnt = new google.maps.Marker({position: point$lcnt, map: map});\n";
                    echo "google.maps.event.addListener(marker$lcnt, function() {infowindow$lcnt.open(map,marker$lcnt);});\n";
                    echo "google.maps.event.addListener(marker$lcnt,'mouseover', function(){infowindow$lcnt.open(map,marker$lcnt);});\n";
                    echo "google.maps.event.addListener(marker$lcnt,'mouseout', function(){infowindow$lcnt.close(map,marker$lcnt);});\n";
                }
            ?>
        }
    </script>
</head>

<body onload='load()'>
	<div id="map_canvas" style="width:1000px;height:550px;"></div>
	</div>
</body>
</html>
